### ISSUE TITLE
Assets are gone??

### ISSUE THREAD

**Issue by aviramartac** [camilb/prometheus-kubernetes#112]
What happened?

**Comment by camilb** [comment]
I'm trying to make the structure more simple. Prometheus rules are now in one manifest: [manifests/prometheus/prometheus-k8s-rules.yaml](https://github.com/camilb/prometheus-kubernetes/blob/master/manifests/prometheus/prometheus-k8s-rules.yaml) and Grafana dashboards are here: [manifests/grafana/grafana-dashboards.cm.yaml](https://github.com/camilb/prometheus-kubernetes/blob/master/manifests/grafana/grafana-dashboards.cm.yaml)

**Comment by aviramartac** [comment]
Hmm okay thanks, so where now for example I can customize Grafana configuration for example? Like disable anonymous access?

**Comment by camilb** [comment]
Grafana has now persistence. Everything you change, persists. Anonymous is disabled by default. First time when you login with `admin:admin` you'll be asked to set a new password.

**Comment by camilb** [comment]
Some configurations can be made directly from the UI

**Comment by aviramartac** [comment]
What about settings that are normally changed via grafana.ini?
