### ISSUE TITLE
Missing pod/container metrics from prometheus,no data point in grafana

### ISSUE THREAD

**Issue by jxsrlsl1234** [camilb/prometheus-kubernetes#136]
my kubernetes version is 1.12.3，

other metrics like nodes and deployments works fine,but pod cannot show data in grafana.
something wrong like following:

![image](https://user-images.githubusercontent.com/29154937/62424737-8b390480-b705-11e9-8f20-d52cb102b075.png)

![image](https://user-images.githubusercontent.com/29154937/62424779-334ecd80-b706-11e9-95a3-7be5e73570f4.png)

I get some important information from the internet that cAdvisor was deprecated after kubernetes 1.12.  I think maybe the pod metrics are from cAdivisor ,so it did not collect the metrics I want, Anybody can solve the problem ,thanks!

**Comment by troian** [comment]
https://github.com/camilb/prometheus-kubernetes/pull/135

**Comment by jxsrlsl1234** [comment]
thanks @troian
