### ISSUE TITLE
Deploy script getting stuck at Waiting for Operator to register custom resource definitions

### ISSUE THREAD

**Issue by adityagundecha** [camilb/prometheus-kubernetes#144]
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+912792b", GitCommit:"912792b", GitTreeState:"clean", BuildDate:"2020-06-16T03:51:52Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

 prometheus-kubernetes   master ●  ./deploy
Enter desired namespace to deploy prometheus [monitoring]:
Creating monitoring namespace.
4Error from server (AlreadyExists): namespaces "monitoring" already exists
1) AWS
2) GCP
3) Azure
4) Custom
Please select your cloud provider:
Deploying on custom providers without persistence
Setting components version
Enter Prometheus Operator version [v0.39.0]:

Enter Prometheus version [v2.19.1]:

Enter Prometheus storage retention period in hours [168h]:

Enter Prometheus storage volume size [40Gi]:

Enter Prometheus memory request in Gi or Mi [1Gi]:

Enter Grafana version [7.0.5]:

Enter Alert Manager version [v0.16.1]:

Enter Node Exporter version [v1.0.1]:

Enter Kube State Metrics version [v1.5.0]:

Enter Prometheus external Url [http://127.0.0.1:9090]:

Enter Alertmanager external Url [http://127.0.0.1:9093]:

Do you want to use NodeSelector to assign monitoring components on dedicated nodes?
Y/N [N]:

Do you want to set up an SMTP relay?
Y/N [N]:

Do you want to set up slack alerts?
Y/N [N]:

Removing all the sed generated files

Deploying Prometheus Operator
serviceaccount/prometheus-operator created
clusterrole.rbac.authorization.k8s.io/prometheus-operator created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-operator created
service/prometheus-operator created
deployment.apps/prometheus-operator created
Waiting for Operator to register custom resource definitions............

Also I would like to know where are the CRD yaml files?

**Comment by camilb** [comment]
fixed in https://github.com/camilb/prometheus-kubernetes/commit/e95af0312d540d484ca0d5a2114462c7131a7a28
