### ISSUE TITLE
how does this compare to prometheus operator?

### ISSUE THREAD

**Issue by VinceMD** [camilb/prometheus-kubernetes#16]
How does that project compare to Prometheus operator and `kube-prometheus`?
What is the roadmap and intention or problem this is trying to solve that might not be solved elsewhere? 

I'm running kube-aws 0.9.7. I've downloaded Prometheus Operator 0.11.1.
I've got the Prometheus running but add to open the ports, editing the kube-aws security groups. Dashboards are showing up in Grafana ok.

**Comment by camilb** [comment]
@VinceMD This project is intended to have a very simple monitoring solution for kubernetes in aws using Prometheus. You can have everything set in less than 2 minutes (prometheus, alertmanager, node-exporter, kube-state-metrics, grafana with custom dashboards and basic alerts for various components)  using an interactive script. Of course you can customise it further, but you have a pretty good start. 

Didn't check the Prometheus operator project lately but my plan is to adapt this project to include the Prometheus operator in the future and make it very simple to setup.

**Comment by camilb** [comment]
Added support for Prometheus Operator in #23
