### ISSUE TITLE
Docker push failing on fedora, unable to complete init.sh

### ISSUE THREAD

**Issue by gnufreex** [camilb/prometheus-kubernetes#20]
Building Grafana Docker image and pushing to dockerhub
Sending build context to Docker daemon 206.8 kB
Step 1/5 : FROM grafana/grafana:4.5.0
 ---> 26ce8e4a4b18
Step 2/5 : MAINTAINER Camil Blanaru <camil@edka.io>
 ---> Running in 9575f1fb31d4
 ---> e877fa9a5a7b
Removing intermediate container 9575f1fb31d4
Step 3/5 : ADD grafana-config/grafana.ini /etc/grafana/grafana.ini
 ---> 0fa652b8ca5e
Removing intermediate container 7ae47a753f8a
Step 4/5 : ADD grafana-dashboards/* /var/lib/grafana/dashboards/
 ---> 4aafce0feadf
Removing intermediate container c9e762439028
Step 5/5 : VOLUME /var/lib/grafana /var/log/grafana /etc/grafana
 ---> Running in e13c2c2541d1
 ---> 39f37b7fa2b0
Removing intermediate container e13c2c2541d1
Successfully built 39f37b7fa2b0
The push refers to a repository [registry.fedoraproject.org/gnufreex/grafana]
80ef99734457: Preparing 
75e389a229a6: Preparing 
5f70bf18a086: Preparing 
c21816ecbe0a: Preparing 
d6a9e60bf7b5: Preparing 
18f9b4e2e1bc: Waiting 
unauthorized: authentication required
docker push failed! perhaps you need to login "gnufreex" to dockerhub?
Password: 
The push refers to a repository [registry.fedoraproject.org/gnufreex/grafana]
80ef99734457: Preparing 
75e389a229a6: Preparing 
5f70bf18a086: Preparing 
c21816ecbe0a: Preparing 
d6a9e60bf7b5: Preparing 
18f9b4e2e1bc: Waiting 
unauthorized: authentication required
docker push failed a second time! exiting.

**Comment by gnufreex** [comment]
Also, all the command line is red after this.

**Comment by camilb** [comment]
I'll make the build image process optional in the future. Also move the Grafana dashboards to ConfigMaps. Until then, here you have a quick fix: #21
