### ISSUE TITLE
Operator reliably creates zombie namespace

### ISSUE THREAD

**Issue by gnufreex** [camilb/prometheus-kubernetes#25]
```
kubectl get namespaces
NAME          STATUS        AGE
default       Active        82d
jenkins       Active        10d
kube-public   Active        82d
kube-system   Active        82d
monitoring    Terminating   2h
monitoring2   Terminating   26m
rabbit        Active        2d

```

I first started operator deploy script, and it hang at 

`
Waiting for Operator to register custom resource definitions.........................................................................................................................................................................................................................................................................................................................................................................................................................^C
`
So I interupted it. Ran teardown script. But namespace is stuck at terminating phase. I can not run the script again until I change namespace variable to monitoring2. 

```kubectl get namespace/monitoring2 -o json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "creationTimestamp": "2017-09-24T21:05:34Z",
        "deletionTimestamp": "2017-09-24T21:14:27Z",
        "name": "monitoring2",
        "resourceVersion": "11461478",
        "selfLink": "/api/v1/namespaces/monitoring2",
        "uid": "1b94baae-a16c-11e7-8350-02a930332a2a"
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Terminating"
    }
}
```

**Comment by camilb** [comment]
Try `kubectl get all -n monitoring` then erase all the objects there. Then, `kubectl delete ns monitoring --grace-period=0 --force`

**Comment by gnufreex** [comment]
Tried that, also tired deleting the controller pod. Doesn't helo. Seems it is this bug.

https://github.com/kubernetes/kubernetes/issues/37278

**Comment by camilb** [comment]
try this:

    kubectl delete servicemonitor $(kubectl get servicemonitor -n monitoring --no-headers | cut -d " " -f1) -n monitoring
    kubectl delete prometheus $(kubectl get prometheus -n monitoring --no-headers | cut -d " " -f1) -n monitoring
    kubectl delete alertmanager $(kubectl get alertmanager -n monitoring --no-headers | cut -d " " -f1) -n monitoring

**Comment by gnufreex** [comment]
kubectl delete servicemonitor $(kubectl get servicemonitor -n monitoring --no-headers | cut -d " " -f1) -n monitoring
No resources found.

kubectl delete prometheus $(kubectl get prometheus -n monitoring --no-headers | cut -d " " -f1) -n monitoring
No resources found.

kubectl delete alertmanager $(kubectl get alertmanager -n monitoring --no-headers | cut -d " " -f1) -n monitoring
the server doesn't have a resource type "alertmanager"
error: resource(s) were provided, but no name, label selector, or --all flag specified

Btw, namespace is empty

**Comment by gnufreex** [comment]
all three puts error: resource(s) were provided, but no name, label selector, or --all flag specified

**Comment by camilb** [comment]
Please contact me on http://slack.kubernetes.io I'm `@camil`
