### ISSUE TITLE
Updating prometheus configuration

### ISSUE THREAD

**Issue by startopscollab** [camilb/prometheus-kubernetes#31]
I need to add additional prometheus configuration, I don't see how I can do it. I found this

update alert rules: add or change the rules in assets/prometheus/rules/ and execute scripts/generate-rules-configmap.sh. Then apply the changes using kubectl apply -f manifests/prometheus/prometheus-k8s-rules.yaml -n monitoring
update grafana dashboards: add or change the existing dashboards in assets/grafana/ and execute scripts/generate-dashboards-configmap.sh. Then apply the changes using kubectl apply -f manifests/grafana/grafana-dashboards.cm.yaml.

Nothing for what i need

**Comment by camilb** [comment]
@startopscollab You mean, a new job?

**Comment by camilb** [comment]
Closed in https://github.com/camilb/prometheus-kubernetes/commit/128633697caa07019d090869ef22ffa94eb72161

**Comment by morganwalker** [comment]
@camilb I don't think this works as expected.  When I run update-config, it successfully rebuilds my prometheus-k8s-0 and prometheus-k8s-1 pods, but localhost:9090 is left with a blank configuration, no targets, and no alerts.  When I run update config, here is my output:

```
Exporting existing configurations


Removing all the sed generated files

Exporting prometheus.yaml key to ./prometheus-k8s-secret/prometheus.yaml
Invalid character in input stream.

Exporting configmaps.json key to ./prometheus-k8s-secret/configmaps.json

Delete prometheus object and secret
prometheus "k8s" deleted


Please make the desired changes in ./prometheus-k8s-secret/prometheus.yaml and press Y to continue.
Y/N [Y]: Y
Error from server (AlreadyExists): secrets "prometheus-k8s" already exists
prometheus "k8s" created
```

When prompted to make my desired changes, I insert my changes into `/tools/custom-configuration/prometheus-k8s-secret/prometheus.yaml` and choose Y.

I'd really like to add some external node_exporter targets but can't figure out how to do so.  Any help would be appreciated.
