### ISSUE TITLE
error in "Waiting for Operator to register custom resource definitions........................"

### ISSUE THREAD

**Issue by abhijt-zanak** [camilb/prometheus-kubernetes#37]
I deployed entire grafana thingy successfully also used for few days when I was trying to apply few changes, I got few errors.
Later, I used ./teardown in order to delete everything and when I started ./deploy, I was getting following error, it stuck at "Waiting for Operator to register custom resource definitions.........................."

- [ ] "abhijitzanak-mac:~ abhijitzanak$ kubectl get pods -n monitoring
- [ ] NAME                                  READY     STATUS             RESTARTS   AGE
- [ ] prometheus-operator-430984089-97sgq   0/1       CrashLoopBackOff   3          1m
- [ ] abhijitzanak-mac:~ abhijitzanak$ kubectl logs -f prometheus-operator-430984089-97sgq -n monitoring
- [ ] ts=2017-11-26T16:07:45Z caller=operator.go:156 component=alertmanageroperator msg="connection established" cluster-version=v1.6.7
- [ ] ts=2017-11-26T16:07:45Z caller=operator.go:257 component=prometheusoperator msg="connection established" cluster-version=v1.6.7
- [ ] ts=2017-11-26T16:07:45Z caller=main.go:147 msg="Unhandled error received. Exiting..." err="Creating CRD: Alertmanager: the server could not find the requested resource"

it is not processing further and not able to deploy entire **prometheus-kubernetes**
Please let me know how I can solved this issue

**Comment by abhijt-zanak** [comment]
also tried 

- [ ] kubectl get crd -o 'jsonpath={.items[*].metadata.name}' | xargs -n 1 | fgrep coreos.com | xargs 

- [ ] kubectl delete crd

the server doesn't have a resource type "crd"

**Comment by camilb** [comment]
Hi @abhijt-zanak I see you're running Kubernetes v1.6.7. Unfortunately versions below 1.7.0 are not supported anymore. `customresourcedefinitions`, aka `crd` were `thirdpartyresources` aka `tpr` before 1.7. I think you were running an older version of Prometheus Operator.

**Comment by abhijt-zanak** [comment]
point taken , will upgrade cluster to 1,7,1 kops. Thanks.
