### ISSUE TITLE
rbac errors on clean deploy

### ISSUE THREAD

**Issue by stevemcghee** [camilb/prometheus-kubernetes#40]
in attempting to deploy this on a 1.7.8-gke.0 cluster with legacy auth enabled (I'm not using RBAC), I get the following:

Deploying Prometheus Operator
serviceaccount "prometheus-operator" created
clusterrolebinding "prometheus-operator" created
service "prometheus-operator" created
deployment "prometheus-operator" created
Error from server (Forbidden): error when creating "manifests/prometheus-operator/prometheus-operator-cluster-role-binding.yaml": clusterroles.rbac.authorization.k8s.io "prometheus-operator" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["thirdpartyresources"], APIGroups:["extensions"], Verbs:["*"]} PolicyRule{Resources:["customresourcedefinitions"], APIGroups:["apiextensions.k8s.io"], Verbs:["*"]} PolicyRule{Resources:["alertmanagers"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["prometheuses"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["servicemonitors"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["*"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["list"]}] user=&{steven.mcghee@mindbodyonline.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
Waiting for Operator to register custom resource definitions.....done!

is GKE supported without RBAC?   

Is it because I am not an Owner of the project?

**Comment by stevemcghee** [comment]
hm, i get: 
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "admin-binding" already exists


Name:         admin-binding
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  cluster-admin
Subjects:
  Kind  Name  Namespace
  ----  ----  ---------

**Comment by stevemcghee** [comment]
here is the full output of ./deploy


Creating 'monitoring' namespace.
Error from server (AlreadyExists): namespaces "monitoring" already exists

1) AWS
2) GCP
3) Azure
Please select your cloud provider:2
Deploying on Google Cloud
Are you deploying in Google Container Engine (GKE)?
Y/N [N]: y
Grant cluster-admin permissions to your current identity
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "admin-binding" already exists
Setting components version
Enter Prometheus Operator version [v0.15.0]:

Enter Prometheus version [v2.0.0]:

Enter Grafana version [4.6.2]:

Enter Alert Manager version [v0.11.0]:

Enter Node Exporter version [v0.15.1]:

Enter Kube State Metrics version [v1.1.0]:

Enter Prometheus external Url [http://127.0.0.1:9090]:

Enter Alertmanager external Url [http://127.0.0.1:9093]:

Do you want to set up an SMTP relay?
Y/N [N]: n

Do you want to set up slack alerts?
Y/N [N]: n

Removing all the sed generated files

Deploying Prometheus Operator
serviceaccount "prometheus-operator" created
clusterrolebinding "prometheus-operator" created
service "prometheus-operator" created
deployment "prometheus-operator" created
Error from server (Forbidden): error when creating "manifests/prometheus-operator/prometheus-operator-cluster-role-binding.yaml": clusterroles.rbac.authorization.k8s.io "prometheus-operator" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["thirdpartyresources"], APIGroups:["extensions"], Verbs:["*"]} PolicyRule{Resources:["customresourcedefinitions"], APIGroups:["apiextensions.k8s.io"], Verbs:["*"]} PolicyRule{Resources:["alertmanagers"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["prometheuses"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["servicemonitors"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["*"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["list"]}] user=&{steven.mcghee@mindbodyonline.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
Waiting for Operator to register custom resource definitions.....done!

Deploying Alertmanager
secret "alertmanager-main" created
service "alertmanager-main" created
alertmanager "main" created

Deploying node-exporter
daemonset "node-exporter" created
service "node-exporter" created

Deploying Kube State Metrics exporter
serviceaccount "kube-state-metrics" created
clusterrolebinding "kube-state-metrics" created
rolebinding "kube-state-metrics" created
deployment "kube-state-metrics" created
service "kube-state-metrics" created
Error from server (Forbidden): error when creating "manifests/kube-state-metrics/kube-state-metrics-rbac.yaml": clusterroles.rbac.authorization.k8s.io "kube-state-metrics" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["resourcequotas"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["resourcequotas"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["replicationcontrollers"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["replicationcontrollers"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["limitranges"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["limitranges"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["daemonsets"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["daemonsets"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["replicasets"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["replicasets"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["list"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["watch"]} PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["list"]} PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["watch"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["list"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["watch"]}] user=&{steven.mcghee@mindbodyonline.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
Error from server (Forbidden): error when creating "manifests/kube-state-metrics/kube-state-metrics-rbac.yaml": roles.rbac.authorization.k8s.io "kube-state-metrics-resizer" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["deployments"], ResourceNames:["kube-state-metrics"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["deployments"], ResourceNames:["kube-state-metrics"], APIGroups:["extensions"], Verbs:["update"]}] user=&{steven.mcghee@mindbodyonline.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]


Deploying Grafana
Enter Grafana administrator username [admin]:
Enter Grafana administrator password: **********
secret "grafana-credentials" created
configmap "grafana-dashboards" created
deployment "grafana" created
service "grafana" created

Deploying Prometheus
serviceaccount "prometheus-k8s" created
rolebinding "prometheus-k8s" created
rolebinding "prometheus-k8s" created
rolebinding "prometheus-k8s" created
clusterrolebinding "prometheus-k8s" created
Error from server (Forbidden): error when creating "manifests/prometheus/prometheus-k8s-rbac.yaml": roles.rbac.authorization.k8s.io "prometheus-k8s" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["get"]}] user=&{steven.mcghee@mindbodyonline.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
Error from server (Forbidden): error when creating "manifests/prometheus/prometheus-k8s-rbac.yaml": roles.rbac.authorization.k8s.io "prometheus-k8s" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]}] user=&{steven.mcghee@mindbodyonline.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
Error from server (Forbidden): error when creating "manifests/prometheus/prometheus-k8s-rbac.yaml": roles.rbac.authorization.k8s.io "prometheus-k8s" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]}] user=&{steven.mcghee@mindbodyonline.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
Error from server (Forbidden): error when creating "manifests/prometheus/prometheus-k8s-rbac.yaml": clusterroles.rbac.authorization.k8s.io "prometheus-k8s" is forbidden: attempt to grant extra privileges: [PolicyRule{NonResourceURLs:["/metrics"], Verbs:["get"]}] user=&{steven.mcghee@mindbodyonline.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*""/version"], Verbs:["get"]}] ruleResolutionErrors=[]
servicemonitor "kubelet" created
servicemonitor "kube-state-metrics" created
servicemonitor "kube-dns" created
servicemonitor "prometheus-operator" created
servicemonitor "node-exporter" created
servicemonitor "kube-scheduler" created
servicemonitor "kube-apiserver" created
servicemonitor "prometheus" created
service "prometheus-k8s" created
servicemonitor "alertmanager" created
configmap "prometheus-k8s-rules" created
servicemonitor "kube-controller-manager" created
storageclass "ssd" created
prometheus "k8s" created

Self hosted
service "kube-controller-manager-prometheus-discovery" created
service "kube-dns-prometheus-discovery" created
service "kube-scheduler-prometheus-discovery" created

Removing local changes

Done


FWIW, I've tried installing prom via helm in the past, which might be why there are dupe roles.  

it's hard to tell if these errors are symptomatic, but the reason i'm looking into it is that I'm getting the following problems:

1) Back-off 5m0s restarting failed container=config-reloader pod=alertmanager-main-0_monitoring(0c960079-dad9-11e7-81a1-42010a80007e): CrashLoopBackOff
   -- seems unrelated:    2017/12/06 23:30:41 no space left on device

2) ./tools/ingress/init.sh didn't seem to work:
googleapi: Error 400: Invalid value for field 'namedPorts[1].port': '0'. Must be greater than or equal to 1, invalid

(I'm just exposing the prometheus-operated and grafana services manually for now)

**Comment by camilb** [comment]
Yes, the deploy script creates this on the first run to attempt resolving this but it looks it doesn't work right anymore. I'll provide a fix soon. Meanwhile, to solve it, please run the fallowing commands:

```bash
gcloud info | grep Account | tr -d '[]' | cut -d ":" -f2

kubectl delete clusterrolebinding admin-binding

kubectl create clusterrolebinding admin-binding --clusterrole=cluster-admin --user=the_result_from_the_first_command
```
Then try deploying again. Should work.

**Comment by stevemcghee** [comment]
ah nice.  that came up clean.  thanks!

**Comment by camilb** [comment]
Fixed in https://github.com/camilb/prometheus-kubernetes/commit/d3997057dda7165a1a67159cfd161eb43c8596f2

**Comment by philicious** [comment]
@camilb I ran into the same errors but for me the problem is the same as described here and onwards https://github.com/coreos/prometheus-operator/issues/357#issuecomment-333273392

my username is reported lowercased by `gcloud info | grep Account` but it actually has capital letters, as correctly reported by `gcloud projects get-iam-policy PROJECT_ID`

getting the correct form isnt easy as it seems via code. as that get-iam-policy command may return multiple users and selecting by role isnt perfect either as roles/container.clusterAdmin would work and also roles/owner

**Comment by camilb** [comment]
@philicious Thanks for reporting this, I'll try to address it in #52

**Comment by camilb** [comment]
You were able to fix it manually for now?

**Comment by philicious** [comment]
@camilb yes I was able to fix it now by hardcoding my user as `GCP_USER` in ./deploy script. 
For getting all users that would have the necessary permissions the following snippet would work:
```
gcloud projects get-iam-policy "kontextr" --format json \
| jq -r '.bindings[] | select(.role == "roles/owner" or .role == "roles/container.clusterAdmin") | .members[]' \
| awk -F':' '{print $2}'
```
as the result isnt distinct, I would suggest presenting the user with a selection of the found users, if there is more than one user found.

**Comment by camilb** [comment]
@philicious Is this somehow better in your use case?

    kubectl create clusterrolebinding admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value core/account)

**Comment by philicious** [comment]
@camilb unfortunately no. the problem is that the username for GCP and used/configured in gcloud, is all lowercase, however the IAM user got created camel-cased.
so deriving the username from gcloud configs wont work and imho the only way is querying the iam-policy.
