### ISSUE TITLE
Grafana shows less than 2 days of graphs (~30hours)

### ISSUE THREAD

**Issue by ssro** [camilb/prometheus-kubernetes#41]
Hi @camilb ,
Not sure if you ran into this issue, but I have a stock deployment of prometheus-kubernetes using the deploy script (no emails/slack integration) on two k8s clusters deployed with kops. One is using the default debian jessie image, the other one is CoreOS. On both, when I look at grafana's graphs I always have the last ~30 hours graphed for both clusters. Worth to mention that the deployment has more than 30 hours.

I think it might be related to how much data retention prometheus has decalred in its config. After deployment on k8s there is a stateful set for prometheus and on the configuration i see `  - '--storage.tsdb.retention=24h'`. How can I change this to a week or more? (Editing the sts on k8s doesn't work, the changes aren't applied)

Thanks!

<img width="972" alt="screen shot 2017-12-06 at 15 45 41" src="https://user-images.githubusercontent.com/13402690/33652579-95339ab4-da9c-11e7-959c-1cf007e0da38.png">

```
NAME                                   READY     STATUS    RESTARTS   AGE
alertmanager-main-0                    2/2       Running   2          9d
alertmanager-main-1                    2/2       Running   2          9d
alertmanager-main-2                    2/2       Running   2          9d
grafana-2372210178-z9wwp               2/2       Running   2          9d
kube-state-metrics-2628134419-pb6lz    2/2       Running   2          9d
node-exporter-3ks0r                    1/1       Running   1          9d
node-exporter-h0l49                    1/1       Running   1          9d
node-exporter-n6wk9                    1/1       Running   1          9d
node-exporter-ss48g                    1/1       Running   1          9d
node-exporter-stvdz                    1/1       Running   1          9d
prometheus-k8s-0                       2/2       Running   2          9d
prometheus-k8s-1                       2/2       Running   2          9d
prometheus-operator-1613319266-9bfzw   1/1       Running   1          9d
```

**Comment by camilb** [comment]
Hi @ssro please edit your prometheus object by running `kubectl edit prometheus k8s -n monitoring` and add   `retention: 168h` just above the `storage:` key.

Fixed in https://github.com/camilb/prometheus-kubernetes/commit/8d943ff8aa7f78c9f570ed915d1eb6423e610dae by adding option to configure storage retention period and storage volume size.

**Comment by ssro** [comment]
Hi @camilb,
Thanks, I redeployed with your changes. Will check again in few days

**Comment by ssro** [comment]
Hi @camilb,

This issue can be closed now. Last 2 days are graphed as opposed to my first screenshot.

Thank you for the fix!

![screen shot 2017-12-09 at 18 24 22](https://user-images.githubusercontent.com/13402690/33795160-69b6a02e-dd0e-11e7-980c-60fc572bcce1.png)

**Comment by morganwalker** [comment]
Thanks for responding! Hmmm, evening after manually bouncing the pods after performing the edit, they still have old values. Here's what I see when I edit:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  clusterName: ""
  creationTimestamp: 2018-04-16T18:44:52Z
  deletionGracePeriodSeconds: null
  deletionTimestamp: null
  generation: 0
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
  resourceVersion: "50577116"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/prometheuses/k8s
  uid: 3fd82646-41a6-11e8-a10c-025eb7287638
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  externalUrl: http://127.0.0.1:9090
  replicas: 2
  resources: null
  retention: 168h
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: prometheus-rulefiles
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: null
  storage:
    requests:
      memory: 2Gi
    volumeClaimTemplate:
      metadata:
        annotations:
          annotation1: prometheus
      spec:
        resources:
          requests:
            storage: 280Gi
        storageClassName: ssd
  version: v2.1.0
```

But on the Pod configs, I see `--storage.tsdb.retention=24h` and no mention of the 280Gi storage. The current PVCs are using 2000Gi and I'm not even sure where that's coming from.

**Comment by morganwalker** [comment]
I updated `"--storage.tsdb.retention=24h` in my `prometheus-k8s` statefulset, which triggered the pods to recreate and take the new config. Now I want to increase the storage request but I can't do that by editing the stateful set. Still performing `kubectl edit prometheus k8s -n monitoring` and making changes doesn't seem to update anything.

**Comment by camilb** [comment]
@morganwalker after changing the storage size you should delete the PersistentVolumeClaims and prometheus pods. New PVCs will be created. 

    kubectl get pvc -n monitoring | grep prometheus | cut -d " " -f 1 | xargs -n 1 kubectl delete pvc -n monitoring
    kubectl delete pod -n monitoring -lapp=prometheus

**Comment by morganwalker** [comment]
It doesn't matter what I edit via `kubectl edit prometheus k8s -n monitoring`, e.g. retention, replicas, storage, it isn't honored. The only thing that has any impact on the pods is when I directly edit the `prometheus-k8s` statefulset, and I can't edit the storage configs via that. I tried `kubectl edit prometheus k8s -n monitoring`, with this edit:

```
storage:
    requests:
      memory: 300Gi
    volumeClaimTemplate:
      metadata:
        annotations:
          annotation1: prometheus
      spec:
        resources:
          requests:
            storage: 300Gi
```

And then running:

```
kubectl get pvc -n monitoring | grep prometheus | cut -d " " -f 1 | xargs -n 1 kubectl delete pvc -n monitoring
kubectl delete pod -n monitoring -lapp=prometheus
```

But the pods are still created with 40Gi PVCs because that's what is defined in the statefulset. From the running k8s statefulset config:

```
"volumeClaimTemplates": [
      {
        "metadata": {
          "name": "prometheus-k8s-db",
          "creationTimestamp": null,
          "annotations": {
            "annotation1": "prometheus"
          }
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "40Gi"
            }
          },
          "storageClassName": "ssd"
```

Again, I really appreciate the continued assistance.

**Comment by morganwalker** [comment]
I worked around this by editing tools/custom-configuration/prometheus-k8s.yaml with the disk size I wanted, running tools/custom-configuration/update-config, blowing away the PVCs attached to the prometheus pods, and restarting the prometheus pods. They'll then attach a PVC the size specified in prometheus-k8s.yaml. Pretty sure that's what you were saying in https://github.com/camilb/prometheus-kubernetes/issues/41#issuecomment-393255457.

Thanks for your assistance!
