### ISSUE TITLE
Deployment on GKE shouldn't use self-hosted controller / scheduler

### ISSUE THREAD

**Issue by hawksight** [camilb/prometheus-kubernetes#48]
Asking for clarification from anyone else as well but on Google Kubernetes Engine (GKE). Are the kube-controller-manager & kube-scheduler even visible?

I cannot see the pods in `kube-system` namespace and I think that's because google manages the master node for you. Therefore the service definitions for [kube-controller-manager](https://github.com/camilb/prometheus-kubernetes/blob/master/manifests/k8s/self-hosted/kube-controller-manager.yaml) and [kube-scheduler](https://github.com/camilb/prometheus-kubernetes/blob/master/manifests/k8s/self-hosted/kube-scheduler.yaml) are not relevant to a deployment on GKE.

I checked using:
```bash
kubectl get pod -n kube-system -l k8s-app=kube-controller-manager
kubectl get pod -n kube-system -l k8s-app=kube-scheduler
```

The result is that you seem to get constant alerts for those two components being down.
Am I right in the above - or by deploying the relevant service, should those two components be monitorable?

## Temp Workaround
If you don't want to deploy those components and therefore not get alerts then you need to do the following:
* Delete controller-manager rules - [kube-controller-manager.rules](https://github.com/camilb/prometheus-kubernetes/blob/master/assets/prometheus/rules/kube-controller-manager.rules)
* Delete scheduler rules - [kube-scheduler.rules](https://github.com/camilb/prometheus-kubernetes/blob/master/assets/prometheus/rules/kube-scheduler.rules)
* Delete controller-manager service - [kube-controller-manager.yaml](https://github.com/camilb/prometheus-kubernetes/blob/master/manifests/k8s/self-hosted/kube-controller-manager.yaml)
* Delete scheduler service - [kube-scheduler.yaml](https://github.com/camilb/prometheus-kubernetes/blob/master/manifests/k8s/self-hosted/kube-scheduler.yaml)
* Delete prometheus, controller manager servicemonitor - [prometheus-k8s-service-monitor-kube-controller-manager.yaml](https://github.com/camilb/prometheus-kubernetes/blob/master/manifests/prometheus/prometheus-k8s-service-monitor-kube-controller-manager.yaml)
* Delete promethus, scheduler servicemonitor - [prometheus-k8s-service-monitor-kube-scheduler.yaml)](https://github.com/camilb/prometheus-kubernetes/blob/master/manifests/prometheus/prometheus-k8s-service-monitor-kube-scheduler.yaml)
* Commit changes to your branch / local copy and then deploy.

Note that I deployed all then sort of hacked away by deleting various elements until the alerts stopped. So the above is untested, but I think it should roughly work looking at the deployment script.

Please let me know if they are visible as I'd love to leave the alerts in if they work properly.

**Comment by camilb** [comment]
Hi @hawksight, thanks for the detailed report. I'm aware that these components are not visible in managed clusters, like GKE and AKS and I'm planning to add a option in the script to skip them.

**Comment by hawksight** [comment]
Thanks for the confirmation @camilb. Everything else worked really nicely on GKE though, so thanks for the good work.
