### ISSUE TITLE
Is it possible to deploy this on a standalone kubernetes cluster

### ISSUE THREAD

**Issue by huang195** [camilb/prometheus-kubernetes#49]
After `git clone` and running the `deploy` script, I get a prompt asking me to enter AWS, GCP, or Azure. Is there no way to use this project for self-hosted k8s cluster?

**Comment by camilb** [comment]
Hi @huang195 it can be adapted. Didn't have a chance to test it outside of these 3 cloud providers. Are you using a persistent volume, like cinder? This should be the only issue deploying it on self-hosted clusters. If you don't need persistence, it can be quickly adapted and I can add an option these days.

**Comment by huang195** [comment]
I'm not using any persistent volume, just using kubeadm to get a cluster up and running and wanted to get some monitoring going.

**Comment by camilb** [comment]
@huang195 Added option to deploy on custom providers in #58.
