### ISSUE TITLE
Add ability to quickly add "nodeSelector" to all deployments

### ISSUE THREAD

**Issue by shaharyakir** [camilb/prometheus-kubernetes#50]
Reason I'm asking for this is to not have the monitoring services/deployments interfere with the main app nodes.

**Comment by camilb** [comment]
Makes sense, I'll come with an update these days.

**Comment by shaharyakir** [comment]
Great, thanks.

**Comment by camilb** [comment]
@shaharyakir addressed in #59. Please let me know if you find any issue.
