### ISSUE TITLE
Connecting Scylla and getting ingress up 

### ISSUE THREAD

**Issue by HannanSolo** [camilb/prometheus-kubernetes#68]
Hello, Gotta say this repository has been a savior for setting up Prometheus and Grafana.
I have scylla setup on my cluster and Prometheus.

But I have no idea how to connect the two, if you have any idea how to connect them or point me to a tutorial, I would appreciate it greatly.

Thanks

**Comment by camilb** [comment]
Hi @HannanSolo, sorry, didn't see it first. Did you manage to set it? Basically you have to configure scylla to expose the metrics, described [here](https://github.com/scylladb/scylla/wiki/Monitor-Scylla-with-Prometheus-and-Grafana) and create a `ServiceMonitor` to make Prometheus scrape these metrics.

**Comment by HannanSolo** [comment]
No problem @camilb ! I was able to get it after a ton of hours and feel like a learned a ton while troubleshooting all thanks to this amazing repo. But I am having a bit of difficulty getting the ingress up and working.

**Comment by camilb** [comment]
The ingress for prometheus?

**Comment by HannanSolo** [comment]
Yes, using the ./init in the ingress folder

**Comment by camilb** [comment]
I think it's broken. Didn't use it for long time and didn't update it, like the rest of components. I'll try to fix it.

**Comment by HannanSolo** [comment]
That would be awesome!! Overall, what is working, saved me probably 20 hours.

**Comment by camilb** [comment]
Do you use any ingress controller, or do you want to create also the controller?

**Comment by camilb** [comment]
Also, the ingress controller was configured for AWS only.

**Comment by camilb** [comment]
If you are using AWS, then check this: https://github.com/camilb/prometheus-kubernetes/tree/fix-ingress

**Comment by HannanSolo** [comment]
Ah, I'm using GKE

**Comment by camilb** [comment]
GKE has its own controller, L7 LB. Please check their documentation: https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer

**Comment by HannanSolo** [comment]
Got it, thank you very much!
