### ISSUE TITLE
Updating new grafana dashboards.

### ISSUE THREAD

**Issue by HannanSolo** [camilb/prometheus-kubernetes#73]
When I create a dashboard in grafana it doesnt save, so i must export it and do the steps here, to import it permanently.

```
update grafana dashboards: add or change the existing dashboards in assets/grafana/ and execute scripts/generate-dashboards-configmap.sh. Then apply the changes using kubectl apply -f manifests/grafana/grafana-dashboards.cm.yaml.
```

and when I go to apply the changes, I get this,
`The ConfigMap "grafana-dashboards" is invalid: metadata.annotations: Too long: must have at most 262144 characters`

**Comment by tigrato** [comment]
this is related with usage of kubectl apply command.

When you use this command it adds an annotation with the previous applied version and as you are applying a large configuration > 262144 characters the resulted annotation `kubectl.kubernetes.io/last-applied-configuration` is invalid. You should not use kubectl apply but instead use kubectl delete followed by kubectl create to avoid creation of this annotation.
