### ISSUE TITLE
Add instructions for updating the Services/Stack to README

### ISSUE THREAD

**Issue by philicious** [camilb/prometheus-kubernetes#75]
The README mentions how to update Grafana Dashboards and Prometheus Alert Rules. 
However it doesnt have infos how to update the stack/services itself. 

- Can one simply pull latest code and re-run `./deploy` script and expect it to deploy any updated services/configs?
- Do you have to run the `./teardown` beforehand and will it persist/reattach the storage and data to the newly created stack then?
- Do you have to manually run `kubectl set image / apply -f` for updating?

**Comment by camilb** [comment]
@philicious I'll add the instructions in a couple of weeks. Usually, I'm running `./teardown` and `./deploy`.

**Comment by vpistis** [comment]
@camilb but `./teardown` delete all data, or not? A command for updating all components without deleting data exists?
tx

**Comment by vpistis** [comment]
@camilb the response is here :) 
I run `./teardown` and `./deploy` and don't delete any information... sorry for the question :) and tanks for your great work.
