### ISSUE TITLE
Grafana 5.x

### ISSUE THREAD

**Issue by paalkr** [camilb/prometheus-kubernetes#80]
Hi

I tried to bump the Grafana version up to v5.1.0-beta1, but then I encountered problems with the persistent storage volumes.

This is the error from the Grafana log
```
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied
```
Reverting back to 4.6.3 resolved the issue.

Any plans for supporting Grafana 5.x?

**Comment by camilb** [comment]
Hi @paalkr fixed in 40700bc5399fb01a674ee0419e2d21d4d8c82af1

**Comment by paalkr** [comment]
Thx, I will try this right away

**Comment by camilb** [comment]
Improvements in #110
