### ISSUE TITLE
Is it possible to call the deploy script without interactive user input?

### ISSUE THREAD

**Issue by grundhoeferj** [camilb/prometheus-kubernetes#83]
Hey 😊
first of all, great work - i like this setup a lot! 

I want to use your setup on an cluster. But i need a possibility to automate the `./deploy` call without interactive user input. Is there a possibility for that? Like passing the parameters directly to the script, e.g.  `./deploy --prometheus-operator-version=<version> ...` or something like that?

**Comment by jdn-za** [comment]
Would also like to have this option, either from cli and/or file/env vars

**Comment by jdn-za** [comment]
turns out you can however use a here document or string https://www.gnu.org/software/bash/manual/bashref.html#Here-Documents

**Comment by goloroden** [comment]
@jdn-za Could you maybe provide an example of how to use a *here document* with the `./deploy` script?

**Comment by goloroden** [comment]
@jdn-za I didn't know *here documents* until now, but I wonder if they work, whether one could not simply redirect stdin to be read from a file, like this:

```shell
$ ./deploy < values.txt
```

Would this work as well?

**Comment by grundhoeferj** [comment]
@jdn-za Would you like to share an example? It would help me a lot! 😊

**Comment by grundhoeferj** [comment]
I solve the problem. Thanks to @jdn-za and @goloroden 😊

My solution is exactly like the approach from @goloroden 

Call:
```shell
$ ./deploy < values.txt
```

The `values.txt` file contains all interactive user input. Each line describes one user input:
```
1
v0.19.0
v2.2.1
168h
40Gi
1Gi
5.1.1
v0.15.0-rc.1
v0.16.0-rc.3
v1.3.1
http://127.0.0.1:9090
http://127.0.0.1:9093
N
N
N
admin
secretPassword
```
