### ISSUE TITLE
Remove Kube-DNS target from prometheus

### ISSUE THREAD

**Issue by DaveNW16HD** [camilb/prometheus-kubernetes#90]
Hi

I'm using this project to monitoring a k8s cluster on azure (using acs-engine). I think Kube-DNS doesn't have it's metric enabled by default. What's the best way to remove the kube-dns target from prometheus. I tried to update the configmap on k8s without much success.

**Comment by camilb** [comment]
Hi @DaveNW16HD sorry for the late reply, here it is:

you can list the `ServiceMonitors` using this command: `kubectl get servicemonitors -n monitoring` 

then delete the one you don't need anymore: `kubectl delete servicemonitor kube-dns -n monitoring`

**Comment by DaveNW16HD** [comment]
Thanks !
