### ISSUE TITLE
Seems like "custom" option ignores some configuration

### ISSUE THREAD

**Issue by fsz1993** [camilb/prometheus-kubernetes#98]
I was trying to deploy using option **_4) Custom_** and it kept creating the prometheus pod with 2Gi required memory for Prometheus.

As I debugged, I found that the script is removing the variables below from the manifest and that causes the issue:
**PROMETHEUS_MEMORY_REQUEST**

I think that the line 3 of the block below is the cause of the issue, as it should be 34 not 31:
"Custom")
            echo "Deploying on custom providers without persistence"
            sed -i -e '1,10d;**31**,47d' manifests/prometheus/prometheus-k8s.yaml;
            sed -i -e '1,12d;47,49d;91,93d' manifests/grafana/grafana.de.yaml;
            break
            ;;
        *) echo invalid option;;

I altered that on my local file and it worked in case anyone is having the same problem.

Regards.

**Comment by camilb** [comment]
Thanks for notice. Fixed in 5f67bce7245104f4b8f4388f8d7576d228e5e010
